2018-01-07 00:00:21,641 - apscheduler.scheduler - base.py[line:936] - WARNING - Error getting due jobs from job store 'default': (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: u'SELECT apscheduler_jobs.id, apscheduler_jobs.job_state \nFROM apscheduler_jobs \nWHERE apscheduler_jobs.next_run_time <= %s ORDER BY apscheduler_jobs.next_run_time'] [parameters: (1515254400.052,)]
2018-01-07 00:00:31,823 - apscheduler.executors.default - base.py[line:120] - WARNING - Run time of job "flush_all_cache (trigger: cron[day='*', hour='0'], next run at: 2018-01-07 00:00:00 CST)" was missed by 0:00:31.823000
